#pragma once
#include "flycc/token.h"
#include <string>
#include <vector>

namespace flycc {

// Hand-written lexer (see docs/architecture.md §3.1 for the rationale on why
// this isn't generated by flex: $/$$ comment rules and {} interpolation
// inside text literals need lookahead flex handles awkwardly).
//
// Text literals (spec §9/§10) are lexed into a Token carrying a list of
// TextPart segments (token.h): literal-text chunks and, for each `{expr}`
// interpolation span, the RAW unparsed source text of `expr`. Per
// architecture.md §3.1 the lexer does NOT parse the sub-expression itself
// (it only does bracket-kind-stack tracking to find the matching `}`); the
// Parser re-lexes/parses each expression span with its own sub-Lexer +
// sub-Parser instance. `{{`/`}}` escapes (§10.2) are handled here and never
// produce an expr part.
class Lexer {
public:
    Lexer(std::string source, std::string filename);

    // Lexes the whole file up front (simplicity over streaming; Fly source
    // files are not expected to be huge).
    std::vector<Token> lexAll();

private:
    std::string src_;
    std::string filename_;
    size_t pos_ = 0;
    int line_ = 1, col_ = 1;

    char peek(int ahead = 0) const;
    char advance();
    bool match(char expected);
    void skipWhitespaceAndComments();
    Token lexOne();
    Token lexNumber();
    Token lexText();
    Token lexIdentOrKeyword();
    Token make(TokKind k, std::string text = "");
    [[noreturn]] void error(const std::string& msg);
};

} // namespace flycc
